const REACT_APP_API_KEY = 'AIzaSyDzt5d5V0PGQvGMpE16KIS4kaPkppOogPg';
const REACT_APP_AUTH_DOMAIN = 'throwing-system.firebaseapp.com';
const REACT_APP_PROJECT_ID = 'throwing-system';
const REACT_APP_STORAGE_BUCKET = 'throwing-system.appspot.com';
const REACT_APP_MESSAGING_SENDER_ID = '556669945920';
const REACT_APP_APP_ID = '1:556669945920:web:8505b6af0e72c9acdbb7a5';

export { REACT_APP_API_KEY, REACT_APP_AUTH_DOMAIN, REACT_APP_PROJECT_ID, REACT_APP_STORAGE_BUCKET, REACT_APP_MESSAGING_SENDER_ID, REACT_APP_APP_ID };
